baseURL = 'https://wostal.eu/'
languageCode = 'en-us'
title = 'Tomasz Wostal'
theme = 'hermit-v2'

googleAnalyticsID = 'G-T7LE7C2JXM'

[author]
  name = "Tomasz Wostal"
#  about = "about-hugo"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  # [[menu.main]]
  #   name = "About"
  #   url = "about-hugo/"
  #   weight = 20

[params]
  homeSubtitle = "The lazy genius"
  
  [[params.social]]
    name = "x"
    url = "https://twitter.com/tomasz_wostal"

  [[params.social]]
    name = "github"
    url = "https://github.com/tomaszwostal"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tomaszwostal"


